spring:
  application:
    name: crypto-vault-service
cvs:
  encryption-key-path: ${ENCRYPTION_KEY_PATH:src/main/resources/encryption.key}
  aes-initialization-vector: ${AES_INITIALIZATION_VECTOR:3a6d40f57eeb6b80}
---
spring:
  cloud:
    config:
      label: main
  config:
    activate:
      on-profile: default
    import: configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_PASSWORD:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

---
spring:
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
    io.openleap: DEBUG
eureka:
  client:
    enabled: false