spring:
  application:
    name: crypto-vault-service
---
spring:
  cloud:
    config:
      label: main
  config:
    activate:
      on-profile: keycloak
    import: configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_PASSWORD:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

---
spring:
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
    io.openleap: DEBUG
eureka:
  client:
    enabled: false
cvs:
  encryption-key-path: src/main/resources/encryption.key
  aes-initialization-vector: 1abc7869-6c7d-4395-9aa3-b1c7d169aa37e4aa2cf0-efe3-420f-a28a-20f3d409c27b